name: Ci Pull Request
on:
  pull_request:
    branches:
      - "*"
jobs:
  common:
    uses: testVinaycicd/github-resuable-actions/.github/workflows/ci-pr.yml@main
    with:
      component_name: user
